// Code generated by github.com/sergei-svistunov/go-ssr. DO NOT EDIT.

package contacts

import (
	"context"
	"io"

	"github.com/sergei-svistunov/go-ssr/pkg/mux"
)

type RouteData struct {
	Emails []string
	Phones []string
}

type RouteDataProvider interface {
	Data(ctx context.Context, r *mux.Request, w mux.ResponseWriter, data *RouteData) error
}

type ssrRoute struct{ dp RouteDataProvider }

func NewRoute(dp RouteDataProvider) mux.Route { return &ssrRoute{dp: dp} }
func (rt *ssrRoute) GetDataContext(ctx context.Context, r *mux.Request, w mux.ResponseWriter, child mux.DataContext) (mux.DataContext, error) {
	dataCtx := &dataContext{
		RouteDataContext: mux.RouteDataContext{
			Child: child,
			Assets: []string{
				"<link href=\"/static/css/pages/users/_userId_/contacts.ebaa73568a9350e8216c.css\" rel=\"stylesheet\">",
				"<script defer=\"defer\" src=\"/static/js/pages/users/_userId_/contacts.ebaa73568a9350e8216c.js\"></script>",
			},
		},
	}

	if err := rt.dp.Data(ctx, r, w, &dataCtx.RouteData); err != nil {
		return nil, err
	}

	return dataCtx, nil
}

func (rt *ssrRoute) GetDefaultRoute(ctx context.Context, r *mux.Request) (string, error) {
	return "", nil
}

type dataContext struct {
	mux.RouteDataContext
	RouteData RouteData
}

func (c *dataContext) Write(w io.Writer) error {
//line index.html:2
	emails := c.RouteData.Emails
//line index.html:1
	phones := c.RouteData.Phones
	if _, err := w.Write(_jvn9rbim0vsbunqtp57fkdco53orrqqht367fspfrmunksm1n890); err != nil {
		return err
	}
//line index.html:7
	for _, phone := range phones {
		if _, err := w.Write(_u7gqvvem62261dt1j9p6b7ql4n71iv9vds5b66o9fnqe1vv1uf3g); err != nil {
			return err
		}
//line index.html:7
		if _, err := mux.WriteHtmlEscaped(w, phone); err != nil {
			return err
		}
		if _, err := w.Write(_2r9972n9hj841mpqco77bjcufn7gtu387u4ppfrdmdeb5tgjm380); err != nil {
			return err
		}
	}
	if _, err := w.Write(_qtsql095u3lcdsk99d34jh6fh4gdu1nkhimlq6nffklglm3859s0); err != nil {
		return err
	}
//line index.html:12
	for _, email := range emails {
		if _, err := w.Write(_u7gqvvem62261dt1j9p6b7ql4n71iv9vds5b66o9fnqe1vv1uf3g); err != nil {
			return err
		}
//line index.html:12
		if _, err := mux.WriteHtmlEscaped(w, email); err != nil {
			return err
		}
		if _, err := w.Write(_2r9972n9hj841mpqco77bjcufn7gtu387u4ppfrdmdeb5tgjm380); err != nil {
			return err
		}
	}
	if _, err := w.Write(_rncqehs0rrovtpco40ldahmg935g3spvmgvfr8754d3q1loqceog); err != nil {
		return err
	}
	return nil
}

var (
	_2r9972n9hj841mpqco77bjcufn7gtu387u4ppfrdmdeb5tgjm380 = []byte{
		0x3c, 0x2f, 0x6c, 0x69, 0x3e,
	}
	_jvn9rbim0vsbunqtp57fkdco53orrqqht367fspfrmunksm1n890 = []byte{
		0x3c, 0x64, 0x69, 0x76, 0x3e, 0x3c, 0x68, 0x33, 0x3e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x3c, 0x2f, 0x68, 0x33, 0x3e, 0x3c, 0x75, 0x6c, 0x3e,
	}
	_qtsql095u3lcdsk99d34jh6fh4gdu1nkhimlq6nffklglm3859s0 = []byte{
		0x3c, 0x2f, 0x75, 0x6c, 0x3e, 0x3c, 0x68, 0x33, 0x3e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x3c, 0x2f, 0x68, 0x33, 0x3e, 0x3c, 0x75, 0x6c, 0x3e,
	}
	_rncqehs0rrovtpco40ldahmg935g3spvmgvfr8754d3q1loqceog = []byte{
		0x3c, 0x2f, 0x75, 0x6c, 0x3e, 0x3c, 0x2f, 0x64, 0x69, 0x76, 0x3e,
	}
	_u7gqvvem62261dt1j9p6b7ql4n71iv9vds5b66o9fnqe1vv1uf3g = []byte{
		0x3c, 0x6c, 0x69, 0x3e,
	}
)
