// Code generated by github.com/sergei-svistunov/go-ssr. DO NOT EDIT.
// Typed reactive client for route /users/_userId_/info

import { createSsrClient } from 'gossr-runtime';

export type ReadVars = {
  lastSeen: string;
}

export type WriteVars = {
}

export const ssr = createSsrClient<ReadVars, WriteVars>({
  wsUrl: typeof window !== 'undefined'
    ? window.location.pathname.replace(/\/$/, '') + '/__ws'
    : '',
  routeKey: '2b2f214e',
});
