// Code generated by github.com/sergei-svistunov/go-ssr. DO NOT EDIT.

package info

import (
	"context"
	"io"

	"github.com/sergei-svistunov/go-ssr/pkg/mux"
)

type RouteData struct {
	User struct {
		Age  uint8
		Info string
	}
}

type RouteDataProvider interface {
	Data(ctx context.Context, r *mux.Request, w mux.ResponseWriter, data *RouteData) error
}

type ssrRoute struct{ dp RouteDataProvider }

func NewRoute(dp RouteDataProvider) mux.Route { return &ssrRoute{dp: dp} }
func (rt *ssrRoute) GetDataContext(ctx context.Context, r *mux.Request, w mux.ResponseWriter, child mux.DataContext) (mux.DataContext, error) {
	dataCtx := &dataContext{
		RouteDataContext: mux.RouteDataContext{
			Child: child,
			Assets: []string{
				"<script defer=\"defer\" src=\"/static/js/pages/users/_userId_/info.a2435ab41912ef57ab27.js\"></script>",
			},
		},
	}

	if err := rt.dp.Data(ctx, r, w, &dataCtx.RouteData); err != nil {
		return nil, err
	}

	return dataCtx, nil
}

func (rt *ssrRoute) GetDefaultRoute(ctx context.Context, r *mux.Request) (string, error) {
	return "", nil
}

type dataContext struct {
	mux.RouteDataContext
	RouteData RouteData
}

func (c *dataContext) Write(w io.Writer) error {
//line index.html:1
	user := c.RouteData.User
	if _, err := w.Write(_a9ttvkip3aga8apcvpseunur3345djdi51n2pk10bfdfjgnsal1g); err != nil {
		return err
	}
//line index.html:5
	if user.Age <= 18 {
		if _, err := w.Write(_vpdk5heaer24etml7ge9711a0mvj4ahrr8p51418dielc0v9la4g); err != nil {
			return err
		}
//line index.html:6
	} else if user.Age <= 30 {
		if _, err := w.Write(_g7sv295h764ok5m5537ahc6f232nq98bloviqv836491mb9h19p0); err != nil {
			return err
		}
//line index.html:8
	} else if user.Age <= 60 {
		if _, err := w.Write(_op9ioepv8l07155uf33djfn67q21vmlv19susgefh9vnirjmd78g); err != nil {
			return err
		}
//line index.html:10
	} else {
		if _, err := w.Write(_l31gs7l9bqjbb89garbu034qb1qhulh2obnf5g8mvdeobdousrhg); err != nil {
			return err
		}
	}
	if _, err := w.Write(_8qi5l5uhb5ugug20bbddeab52h78dc7dfhk5g3dt0pecd4fgsnh0); err != nil {
		return err
	}
//line index.html:13
	if _, err := mux.WriteHtmlEscaped(w, user.Info); err != nil {
		return err
	}
	if _, err := w.Write(_ekjmuf6g35568v78a31kgnldi42g4lfi7ml600gsshsrae2efbb0); err != nil {
		return err
	}
	return nil
}

var (
	_8qi5l5uhb5ugug20bbddeab52h78dc7dfhk5g3dt0pecd4fgsnh0 = []byte{
		0x3c, 0x2f, 0x68, 0x31, 0x3e, 0x3c, 0x70, 0x20, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x3d, 0x22, 0x6d, 0x74, 0x2d, 0x33, 0x22, 0x3e,
	}
	_a9ttvkip3aga8apcvpseunur3345djdi51n2pk10bfdfjgnsal1g = []byte{
		0x3c, 0x68, 0x31, 0x3e, 0x41, 0x67, 0x65, 0x20, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x3a, 0x20,
	}
	_ekjmuf6g35568v78a31kgnldi42g4lfi7ml600gsshsrae2efbb0 = []byte{
		0x3c, 0x2f, 0x70, 0x3e,
	}
	_g7sv295h764ok5m5537ahc6f232nq98bloviqv836491mb9h19p0 = []byte{
		0x3c, 0x73, 0x70, 0x61, 0x6e, 0x3e, 0x31, 0x39, 0x2d, 0x33, 0x30, 0x3c, 0x2f, 0x73, 0x70, 0x61, 0x6e, 0x3e,
	}
	_l31gs7l9bqjbb89garbu034qb1qhulh2obnf5g8mvdeobdousrhg = []byte{
		0x3c, 0x73, 0x70, 0x61, 0x6e, 0x3e, 0x36, 0x30, 0x2b, 0x3c, 0x2f, 0x73, 0x70, 0x61, 0x6e, 0x3e,
	}
	_op9ioepv8l07155uf33djfn67q21vmlv19susgefh9vnirjmd78g = []byte{
		0x3c, 0x73, 0x70, 0x61, 0x6e, 0x3e, 0x33, 0x31, 0x2d, 0x36, 0x30, 0x3c, 0x2f, 0x73, 0x70, 0x61, 0x6e, 0x3e,
	}
	_vpdk5heaer24etml7ge9711a0mvj4ahrr8p51418dielc0v9la4g = []byte{
		0x3c, 0x73, 0x70, 0x61, 0x6e, 0x3e, 0x30, 0x2d, 0x31, 0x38, 0x3c, 0x2f, 0x73, 0x70, 0x61, 0x6e, 0x3e,
	}
)
