// Code generated by github.com/sergei-svistunov/go-ssr. DO NOT EDIT.
// Typed reactive client for route /home

import { createSsrClient } from 'gossr-runtime';

export type ReadVars = {
  displayName: string;
  visitorsBadgeColor: string;
  visitorsOnline: number;
}

export type WriteVars = {
  displayName: string;
}

export const ssr = createSsrClient<ReadVars, WriteVars>({
  wsUrl: typeof window !== 'undefined'
    ? window.location.pathname.replace(/\/$/, '') + '/__ws'
    : '',
  routeKey: '2cc974af',
});
