package generator

import (
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"time"

	"github.com/sergei-svistunov/go-ssr/internal/config"
	"github.com/sergei-svistunov/go-ssr/internal/generator/gobuf"
	"github.com/sergei-svistunov/go-ssr/internal/generator/route"
	"github.com/sergei-svistunov/go-ssr/internal/generator/route/template"
	"github.com/sergei-svistunov/go-ssr/internal/generator/route/template/node"
)

const goFileHeader = "// Code generated by github.com/sergei-svistunov/go-ssr. DO NOT EDIT.\n"

type Generator struct {
	dir            string
	prod           bool
	webDir         string
	webPkgName     string
	depsPackage    string
	depsType       string
	routes         map[string]*route.Route
	assets         *Assets
	projectCmd     *exec.Cmd
	projectCmdDone chan struct{}
	projectCmdEnv  map[string]string
	goRunArgs      string
}

func New(cfg *config.Config) *Generator {
	return &Generator{
		dir:           cfg.Dir,
		prod:          cfg.Prod,
		webDir:        cfg.WebDir,
		webPkgName:    cfg.WebPackage,
		depsPackage:   cfg.DepsPackage,
		depsType:      cfg.DepsType,
		routes:        make(map[string]*route.Route),
		projectCmdEnv: cfg.Env,
		goRunArgs:     cfg.GoRunArgs,
	}
}

func (g *Generator) Analyze() error {
	g.routes = make(map[string]*route.Route)

	assets, err := AssetsFromDir(g.webDir)
	if err != nil {
		return err
	}
	g.assets = assets

	pagesDir := filepath.Join(g.webDir, "pages")
	if err := filepath.WalkDir(pagesDir, func(p string, d fs.DirEntry, err error) error {
		// staticEmbedDirName is a reserved top-level directory under pages/ used
		// as the staging dir for the embedded static-file blob. A real route
		// folder cannot share this name.
		if d.IsDir() && d.Name() == staticEmbedDirName && filepath.Dir(p) == pagesDir {
			return filepath.SkipDir
		}
		if !d.IsDir() || isDirEmpty(p) {
			return nil
		}

		// E01 — reserved path segment __ws.
		// This check runs unconditionally — not only when reactive vars are present.
		if d.Name() == "__ws" {
			// Construct a user-friendly path relative to the module root.
			relPath, _ := filepath.Rel(g.dir, p)
			if runtime.GOOS == "windows" {
				relPath = strings.Replace(relPath, "\\", "/", -1)
			}
			// Use the index.html path as the error location (conventional format).
			indexPath := filepath.Join(p, "index.html")
			relIndex, _ := filepath.Rel(g.dir, indexPath)
			if runtime.GOOS == "windows" {
				relIndex = strings.Replace(relIndex, "\\", "/", -1)
			}
			return fmt.Errorf("%s:1:1: reactive-bindings: route folder \"__ws\" (at %s) is reserved for WebSocket endpoints; rename the folder",
				relIndex, relPath)
		}

		routePath, err := filepath.Rel(pagesDir, p)
		if err != nil {
			return fmt.Errorf("could not determine relative path for route: %w", err)
		}

		if runtime.GOOS == "windows" {
			routePath = strings.Replace(routePath, "\\", "/", -1)
		}

		r, err := route.FromDir(p, func(file string) string {
			result := g.assets.GetImageAsset(path.Join(routePath, file))
			if result == "" {
				return file
			}
			return result
		})
		if err != nil {
			return err
		}

		g.routes[path.Join("/", routePath)] = r

		return nil
	}); err != nil {
		return err
	}

	return nil
}

func (g *Generator) Generate() error {
	hasStatic, staticURLs, err := g.genStaticFiles()
	if err != nil {
		return fmt.Errorf("could not generate static files: %w", err)
	}

	if hasStatic {
		if collisions := g.collisionsWithRoutes(staticURLs); len(collisions) > 0 {
			return fmt.Errorf(
				"static asset URL(s) collide with route path(s): %s — these routes would be silently shadowed by the embedded static handler. Rename the route(s) or change the webpack outputPath to disambiguate",
				strings.Join(collisions, ", "),
			)
		}
	}

	// Run all reactive-bindings validation checks before writing any files.
	if err := g.validateReactiveBindings(); err != nil {
		return err
	}

	if err := g.genHandler(hasStatic); err != nil {
		return fmt.Errorf("could not generate handler: %w", err)
	}

	for rPath, r := range g.routes {
		if err := g.genRoute(rPath, r); err != nil {
			return fmt.Errorf("could not generate route %s: %w", rPath, err)
		}

		if err := g.genRouteDP(rPath, r); err != nil {
			return fmt.Errorf("could not generate route dataprovider %s: %w", rPath, err)
		}

		if err := g.genRouteTSTypes(rPath, r); err != nil {
			return fmt.Errorf("could not generate TS types for route %s: %w", rPath, err)
		}
	}

	return nil
}

// validateReactiveBindings runs all compile-time checks for the reactive-bindings
// feature (E01–E06). Returns the first error encountered.
func (g *Generator) validateReactiveBindings() error {
	// Build a cross-route variable map used by validateSsrBindRefs to distinguish
	// "variable not in this route but in another route" from "variable not declared
	// anywhere". Map: routePath → varName → Variable.
	allRouteVarMaps := make(map[string]map[string]template.Variable, len(g.routes))
	for rPath, r := range g.routes {
		tmpl := r.Template()
		if tmpl == nil {
			continue
		}
		vm := make(map[string]template.Variable, len(tmpl.GetVariables()))
		for _, v := range tmpl.GetVariables() {
			vm[v.Name] = v
		}
		allRouteVarMaps[rPath] = vm
	}

	for _, rPath := range g.getRoutesPaths() {
		r := g.routes[rPath]
		tmpl := r.Template()
		if tmpl == nil {
			continue
		}

		// Build this route's name→Variable map for E07 lookup.
		varMap := allRouteVarMaps[rPath]
		if varMap == nil {
			varMap = make(map[string]template.Variable)
		}

		// E07: ssr:bind on a non-scalar variable type. Must run before
		// E05 so that a non-scalar bind produces the more specific E07 error
		// rather than the generic E05 client-writable error.
		if err := validateSsrBindE07(rPath, tmpl, varMap); err != nil {
			return err
		}

		// E05 + cross-route constraint: ssr:bind without client-writable or
		// ssr:bind referencing a variable in a different route.
		if err := validateSsrBindRefs(rPath, tmpl, allRouteVarMaps); err != nil {
			return err
		}

	}
	return nil
}

// buildReactiveMap builds a map[name]bool of reactive variable names from a
// list of template variables.
func buildReactiveMap(vars []template.Variable) map[string]bool {
	m := make(map[string]bool)
	for _, v := range vars {
		if v.Reactive {
			m[v.Name] = true
		}
	}
	return m
}

func (g *Generator) getRoutesPaths() []string {
	paths := make([]string, 0, len(g.routes))
	for p := range g.routes {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	return paths
}

func (g *Generator) depsPackageName() string {
	return path.Base(g.depsPackage)
}

// collisionsWithRoutes returns any static URL keys that the SSR mux would
// route to a registered route — accounting for dynamic-param segments
// (folders named `_paramName_`). The generated handler tries the static
// handler first, so a colliding route would be silently shadowed.
func (g *Generator) collisionsWithRoutes(staticURLs []string) []string {
	if len(staticURLs) == 0 || len(g.routes) == 0 {
		return nil
	}
	routeSegs := make([][]string, 0, len(g.routes))
	for rp := range g.routes {
		routeSegs = append(routeSegs, splitRoutePath(rp))
	}
	var collisions []string
	for _, u := range staticURLs {
		us := splitRoutePath(u)
		for _, rs := range routeSegs {
			if routeMatchesSegments(rs, us) {
				collisions = append(collisions, u)
				break
			}
		}
	}
	sort.Strings(collisions)
	return collisions
}

func splitRoutePath(p string) []string {
	p = strings.TrimSuffix(p, "/")
	if p == "" {
		return nil
	}
	return strings.Split(strings.TrimPrefix(p, "/"), "/")
}

func routeMatchesSegments(routeSegs, urlSegs []string) bool {
	if len(routeSegs) != len(urlSegs) {
		return false
	}
	for i, rs := range routeSegs {
		if isParamSegment(rs) {
			continue
		}
		if rs != urlSegs[i] {
			return false
		}
	}
	return true
}

func isParamSegment(s string) bool {
	return len(s) >= 3 && s[0] == '_' && s[len(s)-1] == '_' && !strings.Contains(s[1:len(s)-1], "_")
}

func (g *Generator) genHandler(hasStatic bool) error {
	buf := gobuf.New()

	// Determine if any route is reactive (needs WS handler registration).
	var reactiveRoutePaths []string
	for _, rPath := range g.getRoutesPaths() {
		if isReactiveRoute(g.routes[rPath]) {
			reactiveRoutePaths = append(reactiveRoutePaths, rPath)
		}
	}
	hasReactive := len(reactiveRoutePaths) > 0

	buf.WriteStringLn(goFileHeader)
	buf.WriteStringLn("package pages")

	buf.WriteStringLn("import (")
	buf.WriteQuotedString("net/http", "\n")
	if hasReactive {
		buf.WriteQuotedString("context", "\n")
		buf.WriteQuotedString("fmt", "\n")
		buf.WriteQuotedString("sync", "\n")
	}
	buf.WriteString("\n")
	if hasReactive {
		buf.WriteQuotedString("github.com/coder/websocket", "\n")
		buf.WriteQuotedString("github.com/sergei-svistunov/go-ssr/pkg/reactive", "\n")
	}
	buf.WriteQuotedString("github.com/sergei-svistunov/go-ssr/pkg/mux", "\n")
	if g.depsPackage != "" {
		buf.WriteQuotedString(g.depsPackage, "\n")
	}
	buf.WriteString("\n")
	for _, rPath := range g.getRoutesPaths() {
		if rPath == "/" {
			continue
		}
		buf.WriteString(getRoutePackageAlias(rPath))
		buf.WriteQuotedString(path.Join(g.webPkgName, "pages", rPath), "\n")
	}

	buf.WriteStringLn(")")

	// func NewSsrHandler
	if g.depsPackage != "" {
		buf.WriteStringLn("func NewSsrHandler(d *" + g.depsPackageName() + "." + g.depsType + ", opts mux.Options) http.Handler {")
	} else {
		buf.WriteStringLn("func NewSsrHandler(opts mux.Options) http.Handler {")
	}

	// Always use a named variable for the Mux so we can apply WithWSHandlers.
	buf.WriteStringLn("ssrH := mux.New(map[string]mux.Route{")
	for _, rPath := range g.getRoutesPaths() {
		buf.WriteQuotedString(rPath)
		buf.WriteString(": ")
		pkgPrefix := ""
		if rPath != "/" {
			pkgPrefix = getRoutePackageAlias(rPath) + "."
		}
		if g.depsPackage != "" {
			buf.WriteStringLn(pkgPrefix + "NewRoute(" + pkgPrefix + "NewDP(d)),")
		} else {
			buf.WriteStringLn(pkgPrefix + "NewRoute(" + pkgPrefix + "NewDP()),")
		}
	}
	buf.WriteStringLn("}, opts)")

	// Register WebSocket handlers for reactive routes.
	// Multiplexing model: one WS handler per leaf page that has at
	// least one reactive route in its ancestor stack. The handler at the leaf
	// path muxes all reactive ancestors over one WS connection.
	if hasReactive {
		// Compute the set of leaf paths that need WS endpoints.
		// A leaf path needs a WS endpoint if any route in its ancestor stack
		// (including itself) is reactive.
		wsLeafPaths := g.computeWSLeafPaths()

		// Emit one WS handler constructor per leaf path.
		for _, leafPath := range wsLeafPaths {
			ancestors := g.ancestorStack(leafPath)
			g.genWSHandlerCode(buf, leafPath, ancestors)
		}

		buf.WriteStringLn("mux.WithWSHandlers(map[string]http.Handler{")
		for _, leafPath := range wsLeafPaths {
			routeVar := pathToVariable(leafPath)
			buf.WriteQuotedString(wsEndpointPath(leafPath))
			buf.WriteStringLn(": wsHandler" + routeVar + ",")
		}
		buf.WriteStringLn("})(ssrH)")
	}

	if hasStatic {
		buf.WriteStringLn("return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {")
		buf.WriteStringLn("if ssrServeStatic(w, r) { return }")
		buf.WriteStringLn("ssrH.ServeHTTP(w, r)")
		buf.WriteStringLn("})")
	} else {
		buf.WriteStringLn("return ssrH")
	}
	buf.WriteStringLn("}")

	formattedCode, err := buf.Formatted()
	if err != nil {
		return fmt.Errorf("could not format generated code: %w\n%s", err, buf.String())
	}

	if err := os.WriteFile(filepath.Join(g.webDir, "pages", "ssrhandler_gen.go"), formattedCode, 0755); err != nil {
		return fmt.Errorf("could not write handler.go: %w", err)
	}

	return nil
}

func (g *Generator) genRoute(rPath string, r *route.Route) error {
	if r.Template() == nil {
		return nil
	}
	buf := gobuf.New()

	reactive := isReactiveRoute(r)

	// Pre-compute reactive import requirements before emitting the import block.
	// These depend on the template structure but must be known before code emission.
	reactiveMap := buildReactiveMap(r.Template().GetVariables())
	needsStrings := reactive && routeNeedsStringsBuilder(r.Template(), reactiveMap)

	buf.WriteStringLn(goFileHeader)
	buf.WriteString("package ")
	buf.WriteStringLn(path.Base(path.Join("pages", rPath)))

	// Determine whether the reactive write dispatcher will use json.Unmarshal
	// (only when there are client-writable variables).
	hasClientWritableVars := reactive && len(clientWritableVars(r.Template().GetVariables())) > 0

	buf.WriteStringLn("import (")
	buf.WriteQuotedString("context", "\n")
	if hasClientWritableVars {
		buf.WriteQuotedString("encoding/json", "\n")
	}
	buf.WriteQuotedString("io", "\n")
	if len(r.Template().GetForms()) > 0 {
		buf.WriteQuotedString("net/http", "\n")
	}
	if reactive {
		buf.WriteQuotedString("sync", "\n")
	}
	if needsStrings {
		buf.WriteQuotedString("strings", "\n")
	}
	buf.WriteString("\n")
	if len(r.Template().GetForms()) > 0 {
		buf.WriteQuotedString("github.com/sergei-svistunov/go-ssr/pkg/form", "\n")
	}
	buf.WriteQuotedString("github.com/sergei-svistunov/go-ssr/pkg/mux", "\n")
	if reactive {
		buf.WriteQuotedString("github.com/sergei-svistunov/go-ssr/pkg/reactive", "\n")
	}
	buf.WriteStringLn(")")

	routeVariables := r.Template().GetVariables()

	// type RouteData
	buf.WriteStringLn("type RouteData struct {")
	for _, variable := range routeVariables {
		buf.WriteString(getExportedName(variable.Name))
		buf.WriteString(" ")
		buf.WriteStringLn(variable.Type)
	}
	buf.WriteStringLn("}")
	buf.WriteString("\n")

	// Forms types
	for _, form := range r.Template().GetForms() {
		formValuesName := getFormValuesTypeName(form.Name)
		form.Node.DPCtxFieldName = getFormCtxField(form.Name)

		buf.WriteStringLn("type " + formValuesName + " struct {")
		buf.WriteStringLn("	form.BaseFormValues")
		for _, element := range form.Elements {
			fieldName := getExportedName(element.Name)
			buf.WriteString(fieldName)
			switch element.Type {
			case template.FormElementInput:
				if element.IsMultiple {
					buf.WriteStringLn(" form.InputMultiple[" + element.GoType + "]")
				} else {
					buf.WriteStringLn(" form.Input[" + element.GoType + "]")
				}
				for _, n := range element.Nodes {
					if inp, ok := n.(*node.SsrInput); ok {
						inp.FormFieldName = fieldName
					}
				}
			case template.FormElementInputFile:
				if element.IsMultiple {
					buf.WriteStringLn(" form.FileMultiple")
				} else {
					buf.WriteStringLn(" form.File")
				}
				if inp, ok := element.Nodes[0].(*node.SsrInput); ok {
					inp.FormFieldName = fieldName
				}
			case template.FormElementTextarea:
				buf.WriteStringLn(" form.Textarea")
				if ta, ok := element.Nodes[0].(*node.SsrTextarea); ok {
					ta.FormFieldName = fieldName
				}
			case template.FormElementSelect:
				if element.IsMultiple {
					buf.WriteStringLn(" form.SelectMultiple[" + element.GoType + "]")
				} else {
					buf.WriteStringLn(" form.Select[" + element.GoType + "]")
				}
				if sel, ok := element.Nodes[0].(*node.SsrSelect); ok {
					sel.FormFieldName = fieldName
				}
			default:
				return fmt.Errorf("invalid form element type %d for element %q", element.Type, element.Name)
			}
		}
		buf.WriteStringLn("}")
		buf.WriteString("\n")
	}

	// RouteDataProvider
	buf.WriteStringLn("type RouteDataProvider interface{")
	buf.WriteStringLn("Data(ctx context.Context, r *mux.Request, w mux.ResponseWriter, data *RouteData) error")

	if r.Template().GetContentNode() != nil && r.Template().GetContentNode().Default == "" {
		buf.WriteStringLn("DefaultRoute(ctx context.Context, r *mux.Request) (string, error)")
	}

	for _, form := range r.Template().GetForms() {
		buf.WriteStringLn(getFormInitMethod(form.Name) + "(ctx context.Context, r *mux.Request, w mux.ResponseWriter, data *" + getFormValuesTypeName(form.Name) + ") error")
		buf.WriteStringLn(getFormProcessMethod(form.Name) + "(ctx context.Context, r *mux.Request, w mux.ResponseWriter, data *" + getFormValuesTypeName(form.Name) + ") error")
	}

	// Reactive: Subscribe method and Validate<VarName> methods.
	if reactive {
		buf.WriteStringLn("// Subscribe is called once when the WebSocket connection is established.")
		buf.WriteStringLn("// It runs for the connection's lifetime. Respect ctx.Done() for clean shutdown.")
		buf.WriteStringLn("Subscribe(ctx context.Context, r *mux.Request, state *ReactiveState) error")

		for _, v := range clientWritableVars(r.Template().GetVariables()) {
			exportedName := getExportedName(v.Name)
			buf.WriteStringLn("// Validate" + exportedName + " validates a client-initiated write to the " + v.Name + " variable.")
			buf.WriteStringLn("// Return a non-nil error to reject the write; the client receives an err frame.")
			buf.WriteStringLn("Validate" + exportedName + "(ctx context.Context, r *mux.Request, val " + v.Type + ") (" + v.Type + ", error)")
		}
	}

	buf.WriteStringLn("}\n")

	// Reactive: emit ReactiveState struct, renderBlock_KEY helpers, Set<VarName>
	// methods, snapshot, and handleWrite dispatch function.
	// genReactiveStateCode also runs AnnotateBindings (mutating the AST), so
	// routeHasReactiveBlocks can be checked after this call.
	var hasReactiveBlockSites bool
	if reactive {
		if _, err := g.genReactiveStateCode(buf, rPath, r); err != nil {
			return err
		}
		g.genHandleWriteCode(buf, r)
		hasReactiveBlockSites = routeHasReactiveBlocks(r.Template())
	}

	// type ssrRoute
	buf.WriteStringLn("type ssrRoute struct { dp RouteDataProvider }")
	buf.WriteStringLn("func NewRoute(dp RouteDataProvider) mux.Route { return &ssrRoute{dp: dp} }")

	// func (rt *ssrRoute) GetDataContext
	buf.WriteStringLn("func (rt *ssrRoute) GetDataContext(ctx context.Context, r *mux.Request, w mux.ResponseWriter, child mux.DataContext) (mux.DataContext, error) {")

	buf.WriteStringLn("dataCtx := &dataContext{")
	buf.WriteStringLn("	RouteDataContext: mux.RouteDataContext{")
	buf.WriteStringLn("		Child:  child,")
	buf.WriteStringLn("		Assets: []string{")
	for _, asset := range g.assets.GetTags(rPath) {
		buf.WriteQuotedString(asset, ",\n")
	}
	buf.WriteStringLn("		},")
	buf.WriteStringLn("	},")
	buf.WriteStringLn("}")
	buf.WriteString("\n")

	for _, form := range r.Template().GetForms() {
		dCtxFormField := "dataCtx." + getFormCtxField(form.Name)
		buf.WriteStringLn(dCtxFormField + ".BaseFormValues.SetElements([]form.Element{")
		for _, element := range form.Elements {
			buf.WriteStringLn("&" + dCtxFormField + "." + getExportedName(element.Name) + ",")
		}
		buf.WriteStringLn("})")
		buf.WriteString("\n")

		buf.WriteStringLn("if err := rt.dp." + getFormInitMethod(form.Name) + "(ctx, r, w, &" + dCtxFormField + "); err != nil {")
		buf.WriteStringLn("	return nil, err")
		buf.WriteStringLn("}")
		buf.WriteString("\n")
	}

	if len(r.Template().GetForms()) > 0 {
		buf.WriteStringLn("if r.Method == http.MethodPost {")
		buf.WriteStringLn("formId, err := form.Parse(r)")
		buf.WriteStringLn("if err != nil {")
		buf.WriteStringLn("	return nil, err")
		buf.WriteStringLn("}")
		buf.WriteStringLn(`switch formId {`)
		for _, form := range r.Template().GetForms() {
			formField := getFormCtxField(form.Name)
			buf.WriteString("case ")
			buf.WriteQuotedString(form.Name)
			buf.WriteStringLn(":")

			if form.Node.EncType == "multipart/form-data" {
				buf.WriteStringLn(`if !form.IsMultipart(r) {`)
				buf.WriteStringLn(`	return nil, mux.NewHttpError(http.StatusBadRequest, "Content-Type is not multipart/form-data")`)
				buf.WriteStringLn("}")
			} else {
				buf.WriteStringLn(`if form.IsMultipart(r) {`)
				buf.WriteStringLn(`	return nil, mux.NewHttpError(http.StatusBadRequest, "Content-Type is not application/x-www-form-urlencoded")`)
				buf.WriteStringLn("}")
			}

			for _, element := range form.Elements {
				buf.WriteString("dataCtx." + formField + "." + getExportedName(element.Name) + ".Process(r, ")
				buf.WriteQuotedString(element.Name, ", ")

				if form.Node.EncType == node.FormEncTypeMultipart {
					buf.WriteString("true, ")
				} else {
					buf.WriteString("false, ")
				}

				if element.IsRequired {
					buf.WriteString("true")
				} else {
					buf.WriteString("false")
				}
				buf.WriteStringLn(")")
			}

			buf.WriteStringLn("if err := rt.dp." + getFormProcessMethod(form.Name) + "(ctx, r, w, &dataCtx." +
				formField + "); err != nil {")
			buf.WriteStringLn("	return nil, err")
			buf.WriteStringLn("	}")

			buf.WriteStringLn("dataCtx." + formField + ".BaseFormValues.MarkValidated()")
		}
		buf.WriteStringLn("	}")
		buf.WriteStringLn("}")

		buf.WriteString("if err := form.SetCSRFToken(r, w")
		for _, form := range r.Template().GetForms() {
			buf.WriteString(",")
			buf.WriteString("&dataCtx." + getFormCtxField(form.Name) + ".BaseFormValues")
		}
		buf.WriteStringLn("); err != nil {")
		buf.WriteStringLn("	return nil, err")
		buf.WriteStringLn("}")
	}

	buf.WriteStringLn("if err := rt.dp.Data(ctx, r, w, &dataCtx.RouteData); err != nil {")
	buf.WriteStringLn("return nil, err")
	buf.WriteStringLn("}")
	buf.WriteString("\n")
	buf.WriteStringLn("return dataCtx, nil")
	buf.WriteStringLn("}")
	buf.WriteString("\n")

	// func (rt *ssrRoute) GetDefaultRoute
	buf.WriteString("func (rt *ssrRoute) GetDefaultRoute(ctx context.Context, r *mux.Request) (string, error) { return ")
	if nodeContent := r.Template().GetContentNode(); nodeContent != nil {
		if nodeContent.Default == "" {
			buf.WriteString("rt.dp.DefaultRoute(ctx, r)")
		} else {
			buf.WriteQuotedString(nodeContent.Default)
			buf.WriteString(", nil")
		}
	} else {
		buf.WriteString(`"", nil`)
	}

	buf.WriteStringLn("}")

	// type dataContext
	buf.WriteStringLn("type dataContext struct {")
	buf.WriteStringLn("mux.RouteDataContext")
	buf.WriteStringLn("RouteData RouteData")
	for _, form := range r.Template().GetForms() {
		buf.WriteStringLn(getFormCtxField(form.Name) + " " + getFormValuesTypeName(form.Name))
	}
	buf.WriteStringLn("}")

	// func (c *dataContext) Write
	buf.WriteStringLn("func (c *dataContext) Write(w io.Writer) error {")
	for _, variable := range routeVariables {
		buf.WriteStringLn(variable.FilePos())
		buf.WriteString(variable.Name)
		buf.WriteString(":=c.RouteData.")
		buf.WriteStringLn(getExportedName(variable.Name))
	}
	// Inject the ssr-block CSS rule for routes that use reactive block wrappers.
	// Emitted once at the top of the route's HTML output.
	if hasReactiveBlockSites {
		buf.WritePrintString("<style>ssr-block { display: contents; }</style>")
	}
	r.Template().WriteGoCode(buf)
	buf.WriteStringLn("return nil")
	buf.WriteStringLn("}")

	buf.WriteVars()

	formattedCode, err := buf.Formatted()
	if err != nil {
		return fmt.Errorf("could not format generated code: %w\n%s", err, buf.String())
	}

	if err := os.WriteFile(filepath.Join(g.webDir, "pages", rPath, "ssrroute_gen.go"), formattedCode, 0755); err != nil {
		return fmt.Errorf("could not write route.go: %w", err)
	}

	return nil
}

func (g *Generator) genRouteDP(rPath string, r *route.Route) error {
	if r.Template() == nil {
		return nil
	}

	filename := filepath.Join(g.webDir, "pages", rPath, "dataprovider.go")
	if fileExists(filename) {
		// Already exists, skip
		return nil
	}

	buf := gobuf.New()

	buf.WriteString("package ")
	buf.WriteStringLn(path.Base(path.Join("pages", rPath)))

	hasClientWritable := len(clientWritableVars(r.Template().GetVariables())) > 0

	buf.WriteStringLn("import (")
	buf.WriteQuotedString("context", "\n")
	if hasClientWritable {
		buf.WriteQuotedString("errors", "\n")
	}
	buf.WriteString("\n")
	buf.WriteQuotedString("github.com/sergei-svistunov/go-ssr/pkg/mux", "\n")
	if g.depsPackage != "" {
		buf.WriteQuotedString(g.depsPackage, "\n")
	}
	buf.WriteStringLn(")")

	buf.WriteStringLn("var _ RouteDataProvider = &DP{}")

	buf.WriteStringLn("type DP struct{}")

	if g.depsPackage != "" {
		buf.WriteStringLn("func NewDP(d *" + g.depsPackageName() + "." + g.depsType + ") *DP {")
	} else {
		buf.WriteStringLn("func NewDP() *DP {")
	}
	buf.WriteStringLn("	return &DP{}")
	buf.WriteStringLn("}\n")

	if r.Template().GetContentNode() != nil && r.Template().GetContentNode().Default == "" {
		buf.WriteStringLn("func (p *DP) DefaultRoute(ctx context.Context, r *mux.Request) (string, error) {")
		buf.WriteStringLn("	return \"\", nil")
		buf.WriteStringLn("}\n")
	}

	buf.WriteStringLn("// Data is called on initial page load AND on every WebSocket reconnect.")
	buf.WriteStringLn("// Do not rely on r.Method, POST body, or response headers here.")
	buf.WriteStringLn("func (p *DP) Data(ctx context.Context, r *mux.Request, w mux.ResponseWriter, data *RouteData) error {")
	buf.WriteStringLn("	return nil")
	buf.WriteStringLn("}")

	// Reactive stubs.
	if isReactiveRoute(r) {
		buf.WriteString("\n")
		// Subscribe stub.
		buf.WriteStringLn("// Subscribe is called once when the WebSocket connection is established.")
		buf.WriteStringLn("// It runs for the connection's lifetime. Respect ctx.Done() for clean shutdown.")
		buf.WriteStringLn("func (p *DP) Subscribe(ctx context.Context, r *mux.Request, state *ReactiveState) error {")
		buf.WriteStringLn("	// TODO: push state updates here")
		buf.WriteStringLn("	return nil")
		buf.WriteStringLn("}")
		buf.WriteString("\n")

		// Validate stubs for client-writable vars.
		for _, v := range clientWritableVars(r.Template().GetVariables()) {
			exportedName := getExportedName(v.Name)
			buf.WriteStringLn("// Validate" + exportedName + " validates a client-initiated write to " + v.Name + ".")
			buf.WriteStringLn("// The generated default rejects all writes — override to permit them.")
			buf.WriteStringLn("func (p *DP) Validate" + exportedName + "(ctx context.Context, r *mux.Request, val " + v.Type + ") (" + v.Type + ", error) {")
			buf.WriteStringLn(`	return ` + zeroValueForType(v.Type) + `, errors.New("write not implemented")`)
			buf.WriteStringLn("}")
			buf.WriteString("\n")
		}
	}

	formattedCode, err := buf.Formatted()
	if err != nil {
		return fmt.Errorf("could not format generated code: %w\n%s", err, buf.String())
	}

	if err := os.WriteFile(filename, formattedCode, 0755); err != nil {
		return fmt.Errorf("could not write dataprovider.go: %w", err)
	}

	return nil
}

// computeWSLeafPaths returns the sorted set of route paths that should have a
// WS endpoint emitted. A route path qualifies when:
//  1. It is a "leaf" — no other route in g.routes is a strict child of it.
//  2. At least one route in its ancestor stack (including itself) is reactive.
//
// Non-reactive-only subtrees produce no WS endpoint.
func (g *Generator) computeWSLeafPaths() []string {
	routePaths := g.getRoutesPaths()

	// Build a set for quick child-lookup.
	routeSet := make(map[string]bool, len(routePaths))
	for _, p := range routePaths {
		routeSet[p] = true
	}

	isLeaf := func(rPath string) bool {
		prefix := rPath
		if prefix != "/" {
			prefix = rPath + "/"
		}
		for _, p := range routePaths {
			if p != rPath && strings.HasPrefix(p, prefix) {
				return false
			}
		}
		return true
	}

	var wsLeafs []string
	for _, rPath := range routePaths {
		if !isLeaf(rPath) {
			continue
		}
		// Check if any route in the ancestor stack (including this leaf) is reactive.
		ancestors := g.ancestorStack(rPath)
		for _, ancestor := range ancestors {
			if isReactiveRoute(ancestor) {
				wsLeafs = append(wsLeafs, rPath)
				break
			}
		}
	}
	sort.Strings(wsLeafs)
	return wsLeafs
}

// ancestorStack returns the route stack for the given leaf path in root-to-leaf
// order: [root, ...intermediates, leaf]. Only routes present in g.routes are
// included (some intermediate directories may not have their own routes).
func (g *Generator) ancestorStack(leafPath string) []*route.Route {
	var stack []*route.Route
	segments := strings.Split(strings.TrimPrefix(leafPath, "/"), "/")
	if leafPath == "/" {
		segments = []string{}
	}

	// Walk from root to leaf.
	for i := 0; i <= len(segments); i++ {
		var p string
		if i == 0 {
			p = "/"
		} else {
			p = "/" + strings.Join(segments[:i], "/")
		}
		if r, ok := g.routes[p]; ok {
			stack = append(stack, r)
		}
	}
	return stack
}

func pathToVariable(path string) string {
	if path == "" || path == "/" {
		return "_"
	}

	var res string

	for _, segment := range strings.Split(path, "/") {
		if segment == "" {
			continue
		}

		res += strings.ToUpper(string(segment[0])) + segment[1:]
	}

	return res
}

func getFormValuesTypeName(formName string) string {
	return "Form" + getExportedName(formName) + "Values"
}

func getFormInitMethod(formName string) string {
	return "Init" + getExportedName(formName)
}

func getFormProcessMethod(formName string) string {
	return "Process" + getExportedName(formName)
}

func getFormCtxField(formName string) string {
	return "Form" + getExportedName(formName) + "Data"
}

func getRoutePackageAlias(rPath string) string {
	return "route" + pathToVariable(rPath)
}

func getExportedName(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToUpper(string(name[0])) + name[1:]
}

// zeroValueForType returns the Go zero-value literal for a type used in
// Validate<VarName> stubs.
func zeroValueForType(t string) string {
	switch t {
	case "string":
		return `""`
	case "bool":
		return "false"
	default:
		if strings.HasPrefix(t, "*") || strings.HasPrefix(t, "[]") || strings.HasPrefix(t, "map[") {
			// Pointer, slice, and map types have a nil zero value.
			return "nil"
		}
		// Numeric scalar types and named struct types.
		// For numeric types "0" is valid; for structs the caller emits "<Type>{}"
		// but we use a type-specific expression. Struct zero: <Type>{}.
		// Detect if this looks like a numeric type by checking the scalar set.
		numericTypes := map[string]bool{
			"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
			"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
			"uintptr": true, "byte": true, "rune": true,
			"float32": true, "float64": true, "complex64": true, "complex128": true,
		}
		if numericTypes[t] {
			return "0"
		}
		// Named struct or type alias: emit a composite literal zero.
		return t + "{}"
	}
}

func fileExists(filename string) bool {
	_, err := os.Stat(filename)
	return err == nil
}

func fileTime(filename string) (time.Time, error) {
	stat, err := os.Stat(filename)
	if err != nil {
		return time.Time{}, err
	}
	return stat.ModTime(), nil
}

func isDirEmpty(p string) bool {
	entries, err := os.ReadDir(p)
	if err != nil {
		return true
	}
	return len(entries) == 0
}
