// Code generated by github.com/sergei-svistunov/go-ssr. DO NOT EDIT.
// Typed reactive client for route /

import { createSsrClient } from 'gossr-runtime';

export type ReadVars = {
  balance: number;
}

export type WriteVars = {
}

export const ssr = createSsrClient<ReadVars, WriteVars>({
  wsUrl: typeof window !== 'undefined'
    ? window.location.pathname.replace(/\/$/, '') + '/__ws'
    : '',
  routeKey: '8a5edab2',
});
