// Code generated by github.com/sergei-svistunov/go-ssr. DO NOT EDIT.

package pages

import (
	"net/http"

	"github.com/sergei-svistunov/go-ssr/example/internal/model"
	"github.com/sergei-svistunov/go-ssr/pkg/mux"

	routeHome "github.com/sergei-svistunov/go-ssr/example/internal/web/pages/home"
	routeUsers "github.com/sergei-svistunov/go-ssr/example/internal/web/pages/users"
	routeUsers_userId_ "github.com/sergei-svistunov/go-ssr/example/internal/web/pages/users/_userId_"
	routeUsers_userId_Contacts "github.com/sergei-svistunov/go-ssr/example/internal/web/pages/users/_userId_/contacts"
	routeUsers_userId_Info "github.com/sergei-svistunov/go-ssr/example/internal/web/pages/users/_userId_/info"
	routeUsersAdd "github.com/sergei-svistunov/go-ssr/example/internal/web/pages/users/add"
)

func NewSsrHandler(d *model.Model, opts mux.Options) http.Handler {
	ssrH := mux.New(map[string]mux.Route{
		"/":                        NewRoute(NewDP(d)),
		"/home":                    routeHome.NewRoute(routeHome.NewDP(d)),
		"/users":                   routeUsers.NewRoute(routeUsers.NewDP(d)),
		"/users/_userId_":          routeUsers_userId_.NewRoute(routeUsers_userId_.NewDP(d)),
		"/users/_userId_/contacts": routeUsers_userId_Contacts.NewRoute(routeUsers_userId_Contacts.NewDP(d)),
		"/users/_userId_/info":     routeUsers_userId_Info.NewRoute(routeUsers_userId_Info.NewDP(d)),
		"/users/add":               routeUsersAdd.NewRoute(routeUsersAdd.NewDP(d)),
	}, opts)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if ssrServeStatic(w, r) {
			return
		}
		ssrH.ServeHTTP(w, r)
	})
}
