// Code generated by github.com/sergei-svistunov/go-ssr. DO NOT EDIT.

package pages

import (
	"embed"
	"net/http"

	"github.com/sergei-svistunov/go-ssr/pkg/static"
)

//go:embed all:static_embed
var ssrStaticFS embed.FS
var ssrStaticFiles = map[string]static.File{
	"/static/1295669cd4e305c97f2c.woff":                                                                      {ContentType: "font/woff", ETag: "\"efe54401ef52214f\"", EmbedPath: "static_embed/1295669cd4e305c97f2c.woff", Size: 180288, StoredSize: 180288},
	"/static/92ea18a81d737146ff04.woff2":                                                                     {ContentType: "font/woff2", ETag: "\"84a4d15b9e4459b6\"", EmbedPath: "static_embed/92ea18a81d737146ff04.woff2", Size: 134044, StoredSize: 134044},
	"/static/css/main.be79b52a23e6471cbf06.css":                                                              {ContentType: "text/css; charset=utf-8", ETag: "\"a6add0359c456ef0\"", EmbedPath: "static_embed/css/main.be79b52a23e6471cbf06.css.gz", Compressed: true, Size: 274529, StoredSize: 33072},
	"/static/css/pages/users.523e7c5125edd484ecf1.css":                                                       {ContentType: "text/css; charset=utf-8", ETag: "\"f9531f32da27a273\"", EmbedPath: "static_embed/css/pages/users.523e7c5125edd484ecf1.css.gz", Compressed: true, Size: 439, StoredSize: 182},
	"/static/css/pages/users/_userId_/contacts.abeaff4fff07f99844b6.css":                                     {ContentType: "text/css; charset=utf-8", ETag: "\"0ec1bab5100f5e9b\"", EmbedPath: "static_embed/css/pages/users/_userId_/contacts.abeaff4fff07f99844b6.css.gz", Compressed: true, Size: 443, StoredSize: 154},
	"/static/css/vendors-node_modules_bootstrap-icons_font_bootstrap-icons_min_css.5987f184b9dd5c571cda.css": {ContentType: "text/css; charset=utf-8", ETag: "\"988d9cf16bd15b7e\"", EmbedPath: "static_embed/css/vendors-node_modules_bootstrap-icons_font_bootstrap-icons_min_css.5987f184b9dd5c571cda.css.gz", Compressed: true, Size: 87363, StoredSize: 13556},
	"/static/images/home/logo.pnglogo.b11feeeb5df711606111.png":                                              {ContentType: "image/png", ETag: "\"a4065b7a0ba0757e\"", EmbedPath: "static_embed/images/home/logo.pnglogo.b11feeeb5df711606111.png", Size: 59893, StoredSize: 59893},
	"/static/images/logo.pnglogo.b11feeeb5df711606111.png":                                                   {ContentType: "image/png", ETag: "\"a4065b7a0ba0757e\"", EmbedPath: "static_embed/images/logo.pnglogo.b11feeeb5df711606111.png", Size: 59893, StoredSize: 59893},
	"/static/js/bootstrap.e47cb26e34a916f4c2f2.js":                                                           {ContentType: "text/javascript; charset=utf-8", ETag: "\"95057cd8ff061c0b\"", EmbedPath: "static_embed/js/bootstrap.e47cb26e34a916f4c2f2.js.gz", Compressed: true, Size: 142757, StoredSize: 29612},
	"/static/js/luxon.942aca0b9b25e5a111aa.js":                                                               {ContentType: "text/javascript; charset=utf-8", ETag: "\"4bcfd0e11905e1e9\"", EmbedPath: "static_embed/js/luxon.942aca0b9b25e5a111aa.js.gz", Compressed: true, Size: 272919, StoredSize: 60489},
	"/static/js/main.be79b52a23e6471cbf06.js":                                                                {ContentType: "text/javascript; charset=utf-8", ETag: "\"f30d00c4ee586f28\"", EmbedPath: "static_embed/js/main.be79b52a23e6471cbf06.js.gz", Compressed: true, Size: 9575, StoredSize: 2606},
	"/static/js/pages/home.ee578a93bb012732938a.js":                                                          {ContentType: "text/javascript; charset=utf-8", ETag: "\"87d235e088110ba7\"", EmbedPath: "static_embed/js/pages/home.ee578a93bb012732938a.js.gz", Compressed: true, Size: 9279, StoredSize: 2642},
	"/static/js/pages/users.523e7c5125edd484ecf1.js":                                                         {ContentType: "text/javascript; charset=utf-8", ETag: "\"4c88c7fd58399b9a\"", EmbedPath: "static_embed/js/pages/users.523e7c5125edd484ecf1.js.gz", Compressed: true, Size: 9649, StoredSize: 2662},
	"/static/js/pages/users/_userId_/contacts.abeaff4fff07f99844b6.js":                                       {ContentType: "text/javascript; charset=utf-8", ETag: "\"c15ca1ecd4b9d09d\"", EmbedPath: "static_embed/js/pages/users/_userId_/contacts.abeaff4fff07f99844b6.js.gz", Compressed: true, Size: 2268, StoredSize: 823},
	"/static/js/pages/users/_userId_/info.771d1318f84196f63385.js":                                           {ContentType: "text/javascript; charset=utf-8", ETag: "\"54066dbb2da6f1ff\"", EmbedPath: "static_embed/js/pages/users/_userId_/info.771d1318f84196f63385.js.gz", Compressed: true, Size: 8790, StoredSize: 2502},
	"/static/js/vendors.bd957e3da610c60058ff.js":                                                             {ContentType: "text/javascript; charset=utf-8", ETag: "\"6bda225d547e240f\"", EmbedPath: "static_embed/js/vendors.bd957e3da610c60058ff.js.gz", Compressed: true, Size: 182811, StoredSize: 27589},
}

func ssrServeStatic(w http.ResponseWriter, r *http.Request) bool {
	return static.Serve(w, r, ssrStaticFS, ssrStaticFiles)
}
