// Code generated by github.com/sergei-svistunov/go-ssr. DO NOT EDIT.

package pages

import (
	"embed"
	"net/http"

	"github.com/sergei-svistunov/go-ssr/pkg/static"
)

//go:embed all:static_embed
var ssrStaticFS embed.FS
var ssrStaticFiles = map[string]static.File{
	"/static/1295669cd4e305c97f2c.woff":                                  {ContentType: "font/woff", ETag: "\"efe54401ef52214f\"", EmbedPath: "static_embed/1295669cd4e305c97f2c.woff", Size: 180288, StoredSize: 180288},
	"/static/92ea18a81d737146ff04.woff2":                                 {ContentType: "font/woff2", ETag: "\"84a4d15b9e4459b6\"", EmbedPath: "static_embed/92ea18a81d737146ff04.woff2", Size: 134044, StoredSize: 134044},
	"/static/css/713.c2b68d57eaa496d90a5d.css":                           {ContentType: "text/css; charset=utf-8", ETag: "\"4a59978b77df3010\"", EmbedPath: "static_embed/css/713.c2b68d57eaa496d90a5d.css.gz", Compressed: true, Size: 87019, StoredSize: 13467},
	"/static/css/main.f3f597d3fe9a600b89aa.css":                          {ContentType: "text/css; charset=utf-8", ETag: "\"07b5703b933c486d\"", EmbedPath: "static_embed/css/main.f3f597d3fe9a600b89aa.css.gz", Compressed: true, Size: 230772, StoredSize: 30864},
	"/static/css/pages/users.4789bb019e66041c8e22.css":                   {ContentType: "text/css; charset=utf-8", ETag: "\"8c1370fb544e7dc7\"", EmbedPath: "static_embed/css/pages/users.4789bb019e66041c8e22.css.gz", Compressed: true, Size: 69, StoredSize: 93},
	"/static/css/pages/users/_userId_/contacts.0050cdcd5d388d6c8d02.css": {ContentType: "text/css; charset=utf-8", ETag: "\"effc63fc4c603fa5\"", EmbedPath: "static_embed/css/pages/users/_userId_/contacts.0050cdcd5d388d6c8d02.css.gz", Compressed: true, Size: 23, StoredSize: 47},
	"/static/css/vendors.01d2a6ec617e83aef053.css":                       {ContentType: "text/css; charset=utf-8", ETag: "\"9f5445b48f44bd00\"", EmbedPath: "static_embed/css/vendors.01d2a6ec617e83aef053.css.gz", Compressed: true, Size: 258, StoredSize: 198},
	"/static/images/home/logo.pnglogo.b11feeeb5df711606111.png":          {ContentType: "image/png", ETag: "\"a4065b7a0ba0757e\"", EmbedPath: "static_embed/images/home/logo.pnglogo.b11feeeb5df711606111.png", Size: 59893, StoredSize: 59893},
	"/static/images/logo.pnglogo.b11feeeb5df711606111.png":               {ContentType: "image/png", ETag: "\"a4065b7a0ba0757e\"", EmbedPath: "static_embed/images/logo.pnglogo.b11feeeb5df711606111.png", Size: 59893, StoredSize: 59893},
	"/static/js/bootstrap.7eb7f8ba56d073f7cb8b.js":                       {ContentType: "text/javascript; charset=utf-8", ETag: "\"8312812a26e6a9ab\"", EmbedPath: "static_embed/js/bootstrap.7eb7f8ba56d073f7cb8b.js.gz", Compressed: true, Size: 59771, StoredSize: 16286},
	"/static/js/bootstrap.7eb7f8ba56d073f7cb8b.js.LICENSE.txt":           {ContentType: "text/plain; charset=utf-8", ETag: "\"a841710ce93593f5\"", EmbedPath: "static_embed/js/bootstrap.7eb7f8ba56d073f7cb8b.js.LICENSE.txt.gz", Compressed: true, Size: 237, StoredSize: 177},
	"/static/js/luxon.111ed65163c5c5571bb7.js":                           {ContentType: "text/javascript; charset=utf-8", ETag: "\"ae7e67d13dca9eda\"", EmbedPath: "static_embed/js/luxon.111ed65163c5c5571bb7.js.gz", Compressed: true, Size: 70595, StoredSize: 21973},
	"/static/js/main.f3f597d3fe9a600b89aa.js":                            {ContentType: "text/javascript; charset=utf-8", ETag: "\"bb8525a615b6cee4\"", EmbedPath: "static_embed/js/main.f3f597d3fe9a600b89aa.js.gz", Compressed: true, Size: 1488, StoredSize: 858},
	"/static/js/pages/home.5e7dd2c7fdd2d1ed59b6.js":                      {ContentType: "text/javascript; charset=utf-8", ETag: "\"3aa9e3eb580a9a0e\"", EmbedPath: "static_embed/js/pages/home.5e7dd2c7fdd2d1ed59b6.js.gz", Compressed: true, Size: 1644, StoredSize: 927},
	"/static/js/pages/users.4789bb019e66041c8e22.js":                     {ContentType: "text/javascript; charset=utf-8", ETag: "\"4d1033059776b41e\"", EmbedPath: "static_embed/js/pages/users.4789bb019e66041c8e22.js.gz", Compressed: true, Size: 1559, StoredSize: 899},
	"/static/js/pages/users/_userId_/contacts.0050cdcd5d388d6c8d02.js":   {ContentType: "text/javascript; charset=utf-8", ETag: "\"65b32bda9c149b96\"", EmbedPath: "static_embed/js/pages/users/_userId_/contacts.0050cdcd5d388d6c8d02.js.gz", Compressed: true, Size: 0, StoredSize: 23},
	"/static/js/pages/users/_userId_/info.89104f3b680bed7cc4d3.js":       {ContentType: "text/javascript; charset=utf-8", ETag: "\"a2f1a69d750e0bc6\"", EmbedPath: "static_embed/js/pages/users/_userId_/info.89104f3b680bed7cc4d3.js.gz", Compressed: true, Size: 1406, StoredSize: 824},
	"/static/js/vendors.01d2a6ec617e83aef053.js":                         {ContentType: "text/javascript; charset=utf-8", ETag: "\"8a7cba38aa585b43\"", EmbedPath: "static_embed/js/vendors.01d2a6ec617e83aef053.js.gz", Compressed: true, Size: 34385, StoredSize: 11028},
}

func ssrServeStatic(w http.ResponseWriter, r *http.Request) bool {
	return static.Serve(w, r, ssrStaticFS, ssrStaticFiles)
}
