// Code generated by github.com/sergei-svistunov/go-ssr. DO NOT EDIT.

package pages

import (
	"embed"
	"net/http"

	"github.com/sergei-svistunov/go-ssr/pkg/static"
)

//go:embed all:static_embed
var ssrStaticFS embed.FS
var ssrStaticFiles = map[string]static.File{
	"/static/39795c0b4513de014cf8.woff":                                                                      {ContentType: "font/woff", ETag: "\"ba49e844892321d8\"", EmbedPath: "static_embed/39795c0b4513de014cf8.woff", Size: 176032, StoredSize: 176032},
	"/static/b7bcc075b395c14ce8c2.woff2":                                                                     {ContentType: "font/woff2", ETag: "\"cc1e5eda776be5f0\"", EmbedPath: "static_embed/b7bcc075b395c14ce8c2.woff2", Size: 130396, StoredSize: 130396},
	"/static/css/main.a39f9b1eb5039bcdef96.css":                                                              {ContentType: "text/css; charset=utf-8", ETag: "\"31fc204f10993037\"", EmbedPath: "static_embed/css/main.a39f9b1eb5039bcdef96.css.gz", Compressed: true, Size: 272481, StoredSize: 32410},
	"/static/css/pages/users.1794bf4ad6e6eacffefd.css":                                                       {ContentType: "text/css; charset=utf-8", ETag: "\"f9531f32da27a273\"", EmbedPath: "static_embed/css/pages/users.1794bf4ad6e6eacffefd.css.gz", Compressed: true, Size: 439, StoredSize: 182},
	"/static/css/pages/users/_userId_/contacts.ebaa73568a9350e8216c.css":                                     {ContentType: "text/css; charset=utf-8", ETag: "\"0ec1bab5100f5e9b\"", EmbedPath: "static_embed/css/pages/users/_userId_/contacts.ebaa73568a9350e8216c.css.gz", Compressed: true, Size: 443, StoredSize: 154},
	"/static/css/vendors-node_modules_bootstrap-icons_font_bootstrap-icons_min_css.89597b09c5e69f3d5f80.css": {ContentType: "text/css; charset=utf-8", ETag: "\"cc55163817e350e4\"", EmbedPath: "static_embed/css/vendors-node_modules_bootstrap-icons_font_bootstrap-icons_min_css.89597b09c5e69f3d5f80.css.gz", Compressed: true, Size: 86230, StoredSize: 13343},
	"/static/images/home/logo.pnglogo.b11feeeb5df711606111.png":                                              {ContentType: "image/png", ETag: "\"a4065b7a0ba0757e\"", EmbedPath: "static_embed/images/home/logo.pnglogo.b11feeeb5df711606111.png", Size: 59893, StoredSize: 59893},
	"/static/images/logo.pnglogo.b11feeeb5df711606111.png":                                                   {ContentType: "image/png", ETag: "\"a4065b7a0ba0757e\"", EmbedPath: "static_embed/images/logo.pnglogo.b11feeeb5df711606111.png", Size: 59893, StoredSize: 59893},
	"/static/js/bootstrap.9e956bb5a71942fc3218.js":                                                           {ContentType: "text/javascript; charset=utf-8", ETag: "\"ab14aac073385c16\"", EmbedPath: "static_embed/js/bootstrap.9e956bb5a71942fc3218.js.gz", Compressed: true, Size: 142692, StoredSize: 29621},
	"/static/js/luxon.1ed077e024362cfc6deb.js":                                                               {ContentType: "text/javascript; charset=utf-8", ETag: "\"937457c01189cb0d\"", EmbedPath: "static_embed/js/luxon.1ed077e024362cfc6deb.js.gz", Compressed: true, Size: 265299, StoredSize: 58668},
	"/static/js/main.a39f9b1eb5039bcdef96.js":                                                                {ContentType: "text/javascript; charset=utf-8", ETag: "\"e8978d7264033e06\"", EmbedPath: "static_embed/js/main.a39f9b1eb5039bcdef96.js.gz", Compressed: true, Size: 8826, StoredSize: 2346},
	"/static/js/pages/home.5f13d36dca3eb49dffe2.js":                                                          {ContentType: "text/javascript; charset=utf-8", ETag: "\"80029ddd3a8df82e\"", EmbedPath: "static_embed/js/pages/home.5f13d36dca3eb49dffe2.js.gz", Compressed: true, Size: 2575, StoredSize: 908},
	"/static/js/pages/users.1794bf4ad6e6eacffefd.js":                                                         {ContentType: "text/javascript; charset=utf-8", ETag: "\"7551ebf2ac81ef3a\"", EmbedPath: "static_embed/js/pages/users.1794bf4ad6e6eacffefd.js.gz", Compressed: true, Size: 8253, StoredSize: 2297},
	"/static/js/pages/users/_userId_/contacts.ebaa73568a9350e8216c.js":                                       {ContentType: "text/javascript; charset=utf-8", ETag: "\"127ae73246b53e63\"", EmbedPath: "static_embed/js/pages/users/_userId_/contacts.ebaa73568a9350e8216c.js.gz", Compressed: true, Size: 2278, StoredSize: 820},
	"/static/js/pages/users/_userId_/info.a2435ab41912ef57ab27.js":                                           {ContentType: "text/javascript; charset=utf-8", ETag: "\"66de67a2c3dc287d\"", EmbedPath: "static_embed/js/pages/users/_userId_/info.a2435ab41912ef57ab27.js.gz", Compressed: true, Size: 1388, StoredSize: 598},
	"/static/js/vendors.c44cd0e6d374429cb0f9.js":                                                             {ContentType: "text/javascript; charset=utf-8", ETag: "\"28c33ab0688d35df\"", EmbedPath: "static_embed/js/vendors.c44cd0e6d374429cb0f9.js.gz", Compressed: true, Size: 158145, StoredSize: 21108},
}

func ssrServeStatic(w http.ResponseWriter, r *http.Request) bool {
	return static.Serve(w, r, ssrStaticFS, ssrStaticFiles)
}
